on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"
          include-prerelease: true
      - run: dotnet build
      - run: dotnet test
